### ISSUE TITLE
token, etc based Auth

### ISSUE THREAD

**Issue by Skeyelab** [SmashingDashboard/smashing#19]
I am currently using the HTTP basic auth method for securing my dashboard, but I want to deploy it using this: https://github.com/guysoft/FullPageOS and HTTP auth isnt supported.

I'm hoping to be able to pass a parameter in the URL that if its not there, the dashboard is not displayed.

Any tips on this?

**Comment by tylermauthe** [comment]
Here's an example:
https://github.com/SmashingDashboard/smashing/wiki/How-to:-Add-authentication#authenticating-via-auth_token-querystring-param

To do this in a sane way relies on adding sessions to the application, so all requests beyond the initial are authenticated by a stored token in your session.

Hope this helps!
