### ISSUE TITLE
Is it possible to modify data object in onData, and have the result be rendered?

### ISSUE THREAD

**Issue by Zazcallabah** [SmashingDashboard/smashing#22]
I'm making a widget displaying deployment information for a list of servers.
Incoming data is a list of objects containing a timestamp, and I'm trying to transform the timestamp before it is displayed. (So the user sees "2h ago" instead of "2016-11-26T13:48:01Z")

How can this be done?

I'm currently trying to solve it by transforming the incoming data in the overloaded onData method, but the result doesnt update past the first time the event is fired.

Example:
Widget coffee file 

    class Dashing.Test extends Dashing.Widget
      state: 0
      onData: (data) =>
        data.test = @state++

Widget html file

    <h1 class="title">Works?</h1>
    <p data-bind="test"></p>

**Comment by Zazcallabah** [comment]
Currently I'm doing the transformation in the job, but I would prefer to do it in the widget.

**Comment by kinow** [comment]
Your widget will get the receivedData method called once, during its initialization. The receivedData method, on its turn, will call the onData that you added to your test widget.

If you need the value to change, you will need a job, or call the API from an external agent.

If you do not need the value to change, but just want to format the date, for example, you can do that in CoffeeScript/JavaScript when you receive the data. But that value won't change unless you update it in some way.

Hope that helps
Bruno

**Comment by Zazcallabah** [comment]
So onData is only called once? I thought it was called once per

    SCHEDULER.every '30s' do
      //data = httpget
     send_event('id', data)
    end

**Comment by kinow** [comment]
If you have that in a job. Doing only with the widget, AFAICT, you will get it called once.

**Comment by Zazcallabah** [comment]
So it will get called every 30 seconds, good.
But can I modify the data parameter in the onData function and have the result show up on the dashboard? All examples I've found only ever add and remove classes from elements, and that feels like a weird way of solving this. I'd much rather transform the data before it is bound to the template, but that doesnt seem to happen.

**Comment by Zazcallabah** [comment]
to be clear, this is what I have:

job.rb:

    SCHEDULER.every '30s' do
      data = getData('http://externalapiurl/api/deployDate') // data = {"date":"2016-11-21T10:00:00Z"}
      send_event('id', data)
    end

statuswidget.coffee:

    class Dashing.ServerStatus extends Dashing.Widget
      since: (str) =>
        currentUTC = new Date().toISOString()
        a = Date.parse(str)
        b = Date.parse(currentUTC)
        s = (b-a)/1000
        if s < 90
          return Math.round(s)+"s"
        else if s < 90*60
          return Math.round(s/60)+"m"
        else if s < 30*3600
          return Math.round(s/3600)+"h"
        else
          return Math.round(s/(3600*24))+"d"

      onData: (data) =>
        if data && data.date
          data.since = @since( data.date )

statuswidget.html:

    <h1 class="title" data-bind="title"></h1>
    <p data-bind="since"></p>

**Comment by Zazcallabah** [comment]
I've set a breakpoint and I can see that it sets the 'since' property every time, but it never updates the text on screen. Data binding to the 'date' property obviously works and updates as is expected.

**Comment by kinow** [comment]
Tried your example, here's what I modified to get it quite working.

1. In statuswidget.coffee, renamed your class to Statuswidget, or rename the file to serverstatus.coffee and fix the case (or add a space to the file name)
2. In statuswidget.coffee, renamed the since function to something else, to avoid conflicts with CoffeeScript 

Here's what I have

job.rb:
```
SCHEDULER.every '3s' do
  # Generate some random data to see the widget behavior
  from = Time.parse("2016-01-01 00:00:01")
  to = Time.parse("2016-06-01 00:00:01")
  random_time = Time.at((from.to_f - to.to_f)*rand + to.to_f)
  #data = {"date":"2016-11-21T10:00:00Z"}
  data = {"date": random_time.strftime("%Y-%m-%dT%H:%M:%SZ")}
  puts data
  send_event('id', data)
end
```
statuswidget.coffee:

```
class Dashing.Serverstatus extends Dashing.Widget

  sinceFn: (str) =>
    currentUTC = new Date().toISOString()
    a = Date.parse(str)
    b = Date.parse(currentUTC)
    s = (b-a)/1000
    if s < 90
      return Math.round(s)+"s"
    else if s < 90*60
      return Math.round(s/60)+"m"
    else if s < 30*3600
      return Math.round(s/3600)+"h"
    else
      return Math.round(s/(3600*24))+"d"

  onData: (data) ->
    if data && data.date
      data.since = @sinceFn(data.date)
      console.log(data)
```

statuswidget.html:

```
<h1 class="title" data-bind="title"></h1>
<p data-bind="since"></p>
```

statuswidget.scss (not important):

```
// ----------------------------------------------------------------------------
// Sass declarations
// ----------------------------------------------------------------------------
$background-color:  #47bbb3;
$value-color:       #fff;

$title-color:       rgba(255, 255, 255, 0.7);

// ----------------------------------------------------------------------------
// Widget-serverstatus styles
// ----------------------------------------------------------------------------
.widget-serverstatus {

  background-color: $background-color;

  .title {
    color: $title-color;
  }

  .value {
    color: $value-color;
  }

}
```

**Comment by kinow** [comment]
You should see the widget being displayed with the first "since" value. But it won't change. Even though you are sending the value every 3 seconds, or 30 seconds, the coffee script onData method will be the last called, and if you alter the data value, that simply gets discarded without being served in the UI.

**Comment by kinow** [comment]
Look at the console, and at the JS console. You should see the data values.

In the onData method, you can actually set the new since value in the UI as follows:

statuswidget.coffee:
```
class Dashing.Serverstatus extends Dashing.Widget

  sinceFn: (str) =>
    currentUTC = new Date().toISOString()
    a = Date.parse(str)
    b = Date.parse(currentUTC)
    s = (b-a)/1000
    if s < 90
      return Math.round(s)+"s"
    else if s < 90*60
      return Math.round(s/60)+"m"
    else if s < 30*3600
      return Math.round(s/3600)+"h"
    else
      return Math.round(s/(3600*24))+"d"

  onData: (data) ->
    if data && data.date
      since = @sinceFn(data.date)
      console.log(data)
      container = $(@node).find('.value')
      container.text(since)

```

And that should get updated every 3 seconds, with the random since value. Then you can remove debug messages, and fix the job.

Here's what the dashboard file looks like too.

```
<div class="gridster">
  <ul>
    <li data-row="1" data-col="1" data-sizex="1" data-sizey="1">
      <div data-id="id" data-view="Serverstatus" data-title="Status Widget"></div>
    </li>
  </ul>
</div>

```

**Comment by Zazcallabah** [comment]
It's that line `container = $(@node).find('.value')` that is my problem. I can't use that because I'm trying to set individual properties on objects in a list of values.

I don't think I'm explaining this very well.

This is the version that is currently running in production, css omitted, urls changed: https://gist.github.com/Zazcallabah/5beb88a114e0fe71961b743009dca429
I'm trying to move the since method from server to client. From ruby to coffee. From what you are saying this doesn't seem possible?

**Comment by kinow** [comment]
Thanks for the example. Not sure if that's possible, that's just the way I'm used to write widgets/jobs, and also after reading parts of the Dashing source code.

>It's that line container = $(@node).find('.value') that is my problem. I can't use that because I'm trying to set individual properties on objects in a list of values.

I think the objects in a list of values are your dependencies? If so, isn't there any property that can be used as a link between the dependency, and the deploy date used for the since? (given I understood the example correctly).

In other words, there's really no way to do that by changing objects in the screen via CoffeeScript/JavaScript? By adding other attributes to some elements in your list of values perhaps?

**Comment by Zazcallabah** [comment]
Not really, I'm afraid. I suppose we could add an arbitrary id to each element in the list, and find them that way, but that isn't really better than what we have currently.

What I really would like is another overridable method that can transform the data before batman does its thing.

Ok, this works https://github.com/Zazcallabah/smashing/commit/a61c20be2d519591ef64960734b1b2bd70893fbe

Is this something you would be open to see in a pull request, or should I switch to referencing my own fork?

In any case, thanks for the help. : )

**Comment by kinow** [comment]
Don't see why not. I think it wouldn't break the current behavior, and it could help other users with similar case as yours. But would be nice if @tylermauthe could also take a look, both at implementation and naming of the method. In case he knows another way, or if the naming makes sense. I'm fine adding it given we maintain backward compatibility :+1:
