### ISSUE TITLE
Is it possible to create dynamically links on widgets?

### ISSUE THREAD

**Issue by Johnathan316** [SmashingDashboard/smashing#23]
Hello,

I found two ways to make a widget clickable, but for both of this ways I have to use static links (link has to be set in the <li> tag at the dashboard.erb file.
So, I want to manipulate the link dynamically in the job file (dashboard.rb) and send it with the send_event() function to the widgets (like the color of the widget or some text). Is there any way to do so?

**Comment by kinow** [comment]
I think so @Johnathan316 

Never had to do that myself, but I bet you can do that by looking at the existing Widgets. You can send the link value in the job (dashboard.rb), and then manipulate the DOM and change the onclick value via CoffeeScript (i.e. in the file yourcustomwidget.coffee).

Something like (not tested):

```
# yourcustomwidget.coffee
...
onData: (data) ->
  var node = $(@node);
  var newLink = data.mylink; # your job is sending the mylink value
  var currentLink = node.attr(onclick); # I think that's how you'd get the onclick attribute?
  ... compare, and set if different (as changing DOM is expensive and can slow down :) 
```

Hope that helps
Bruno
